version: '3'

services: 
  backend:
    # Name the service container
    image: service-pusher
    container_name: service-pusher
    build: ./
    restart: on-failure

    volumes:
      - ./:/webapps/service
      - /var/log/apps/:/var/log/apps/

    ports:
      - 4066:5005

    networks:
     - same-network

    command: supervisord -n -c /etc/supervisor.d/supervisord.conf

  workers:
    # Name the service container
    image: worker-pusher-service
    container_name: worker-pusher-service
    build: ./
    restart: on-failure
    volumes:
      - ./:/webapps/service
      - /var/log/apps/:/var/log/apps/
    networks:
      - same-network

    command: supervisord -n -c /etc/supervisor.d/worker-supervisord.conf

networks:
  same-network:
    external: true
