[unix_http_server]
file=/run/supervisord.sock   ; (the path to the socket file)

[supervisord]
logfile=/var/log/supervisord.log ; (main log file;default $CWD/supervisord.log)
loglevel=info                ; (log level;default info; others: debug,warn,trace)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock ; use a unix:// URL  for a unix socket

[program:the-cua-tui-service]
command=uwsgi -psgi /etc/uwsgi/uwsgi.ini
directory=/webapps/the-cua-tui-service
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/apps/base.log

# Comment if you dont need celery
[program:iapi_celery]
command=celery --app code.tasks worker -Q voter_celery -l DEBUG -c 4
directory=/webapps/base-service
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/apps/base_celery.log
logfile_maxbytes=10MB
logfile_backups=1
